### ISSUE TITLE
Switch from darglint to pydoclint

### ISSUE THREAD

**Issue by cidrblock** [ansible/tox-ansible#230]
```
  - repo: https://github.com/jsh9/pydoclint
    rev: 0.3.2
    hooks:
      - id: pydoclint
        args:
          - "--config=pyproject.toml
  ```

```
[tool.pydoclint]
allow-init-docstring = true
arg-type-hints-in-docstring = false
check-return-types = false
style = 'google'
```

(darglint is deprecated and ruff doesn't have support yet)
